### PR TITLE
Remove lombok and minor fixes

### LINKED ISSUE #24: Remove lombok as a dependency
Lombok is used currently in the project for rapid development, but should be removed as soon as we are getting ready for the first release of the tool.

For a better way to handle models and builders, we can use instead the [immutables](https://immutables.github.io/) library if required at all.

For the modles, moving them to interface only will also make them more flexible on what we can do with the implementation.

### PR DESCRIPTION
**Pull request by magicDGS**
- Remove lombok completely to have more control over the code (closes #24)
- Fix property package name (named as propertie before)
- Fix spanish setter on localized data

### CODE REVIEW

File: model-utils/src/main/java/io/github/ygojson/model/utils/data/CardUtils.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
+package io.github.ygojson.model.utils.data;
+
+import java.util.Set;
+
+import io.github.ygojson.model.data.Card;
+
+public class CardUtils {
```
Comment (magicDGS) [inline model-utils/src/main/java/io/github/ygojson/model/utils/data/CardUtils.java:7]: This should go to a different PR

File: tools/src/main/java/io/github/ygojson/tools/Application.java [hunk 2]
```diff
@@ -26,13 +25,19 @@
...
-@RequiredArgsConstructor
 public class Application implements CommandLineRunner, ExitCodeGenerator {
 
+	private static final Logger log = LoggerFactory.getLogger(Application.class);
+
 	private final CommandLine.IFactory factory;
 	private final ParentCli parentCli;
 	private int exitCode = ParentCli.UNEXPECTED_ERROR_CODE;
 
+	public Application(ParentCli parentCli, CommandLine.IFactory factory) {
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/Application.java:36]: Make final

File: tools/src/main/java/io/github/ygojson/tools/cli/CliCommand.java [hunk 3]
```diff
@@ -15,10 +16,11 @@
  * @param <I> input type
  * @param <T> tool type
  */
-@Slf4j
 abstract class CliCommand<I, T extends YgoJsonTool<I>>
 	implements Callable<Integer> {
 
+	private Logger log = LoggerFactory.getLogger(getClass());
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/cli/CliCommand.java:22]: Make static final

File: tools/src/main/java/io/github/ygojson/tools/cli/GenerateDocumentationCli.java [hunk 4]
```diff
@@ -13,18 +11,20 @@
...
 	name = "documentation",
 	description = "generates the documentation for the YGOJSON models"
 )
-@RequiredArgsConstructor
 public class GenerateDocumentationCli
 	extends CliCommand<GenerateDocsTool.Input, GenerateDocsTool> {
 
 	private final GenerateDocsTool tool;
 
+	public GenerateDocumentationCli(GenerateDocsTool tool) {
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/cli/GenerateDocumentationCli.java:24]: Make final

File: tools/src/main/java/io/github/ygojson/tools/common/YgoJsonToolException.java [hunk 5]
```diff
@@ -1,16 +1,29 @@
...
 
-import lombok.experimental.StandardException;
-
 /**
  * Runtime exception for the YGOJSON tools.
  */
-@StandardException
 public class YgoJsonToolException extends RuntimeException {
 
+	public YgoJsonToolException(String message) {
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/common/YgoJsonToolException.java:8]: Make params final

File: tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/Categories.java [hunk 6]
```diff
@@ -1,10 +1,7 @@
 package io.github.ygojson.tools.dataprovider.impl.yugipedia.model.api;
 
-import lombok.Data;
-
-@Data
 public class Categories {
 
-	private int ns;
-	private String title;
+	public int ns;
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/Categories.java:5]: I would say that it is better for all these models to make them private still and add the getters with the IDE

File: tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/QueryResponse.java [hunk 7]
```diff
@@ -4,35 +4,32 @@
...
+	public Query query;
 
 	/**
 	 * Untyped warnings.
 	 */
-	private JsonNode warnings;
+	public JsonNode warnings;
 
-	@Data
 	public static class Query {
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/QueryResponse.java:25]: Let's extract also the `Query`

File: tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/params/PipeSeparated.java [hunk 8]
```diff
@@ -2,13 +2,9 @@
 
 import java.util.List;
 
-import lombok.AccessLevel;
-import lombok.RequiredArgsConstructor;
-
 /**
  * Helper method to join properly multiple parameters with pipes.
  */
-@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/params/PipeSeparated.java:11]: In this class, create the private constructor and change the current one for a create method

File: tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/params/SortDirection.java [hunk 9]
```diff
@@ -1,17 +1,18 @@
...
  * Contains only sort directions used on YGOJSON.
  */
-@RequiredArgsConstructor
 public enum SortDirection {
 	OLDER("older"),
 	NEWER("newer");
 
 	private final String value;
 
+	SortDirection(String value) {
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/params/SortDirection.java:12]: Make private

File: tools/src/main/java/io/github/ygojson/tools/dataprovider/utils/client/ClientFactory.java [hunk 10]
```diff
@@ -23,6 +21,11 @@ public class ClientFactory {
 	private final ObjectMapper jsonMapper;
 	private final ApplicationInfo info;
 
+	public ClientFactory(ObjectMapper jsonMapper, ApplicationInfo info) {
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/dataprovider/utils/client/ClientFactory.java:24]: Make params private

File: tools/src/main/java/io/github/ygojson/tools/dataprovider/utils/client/RateLimitInterceptor.java [hunk 11]
```diff
@@ -4,17 +4,19 @@
...
 import okhttp3.MediaType;
 import okhttp3.Response;
 import okhttp3.ResponseBody;
 
-@RequiredArgsConstructor
 class RateLimitInterceptor implements Interceptor {
 
 	private final RateLimiter rateLimiter;
 
+	public RateLimitInterceptor(RateLimiter rateLimiter) {
```
Comment (magicDGS) [inline tools/src/main/java/io/github/ygojson/tools/dataprovider/utils/client/RateLimitInterceptor.java:16]: Make param private

**Review by magicDGS — COMMENTED** [review]
Some stuff to improve the code style

File: tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/params/SortDirection.java (hunk 9 above)
Comment (magicDGS) [reply tools/src/main/java/io/github/ygojson/tools/dataprovider/impl/yugipedia/model/api/params/SortDirection.java:12]: That's redundant on enums, not fixing
